USE [master]
GO

/****** Object:  Database [Shopping]    Script Date: 15/03/2018 16:50:15 ******/
CREATE DATABASE [Shopping]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Shopping', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Shopping.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Shopping_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Shopping_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Shopping] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Shopping].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Shopping] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Shopping] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Shopping] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Shopping] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Shopping] SET ARITHABORT OFF 
GO

ALTER DATABASE [Shopping] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Shopping] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Shopping] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Shopping] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Shopping] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Shopping] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Shopping] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Shopping] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Shopping] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Shopping] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Shopping] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Shopping] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Shopping] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Shopping] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Shopping] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Shopping] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Shopping] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Shopping] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Shopping] SET  MULTI_USER 
GO

ALTER DATABASE [Shopping] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Shopping] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Shopping] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Shopping] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Shopping] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Shopping] SET QUERY_STORE = OFF
GO

USE [Shopping]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Shopping] SET  READ_WRITE 
GO

